version: '3.7'
services:
  visualizer:
    image: dockersamples/visualizer:stable
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8090:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
networks:
  app-network:
    external: true