version: '3.7'
services:
  mysql:
    image: mysql:latest
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - 3306:3306
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "mysql-log:/logs"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-network
# docker network create --driver overlay app-network
networks:
  app-network:
    external: true
# docker volume create --driver local mysql-data =>  "Mountpoint": "/var/lib/docker/volumes/mysql-data/_data"
volumes:
  mysql-data:
    external: true
    name: mysql-data
  mysql-log:


